            - name: Save to Software Heritage
  # You may pin to the exact commit or the version.
  # uses: sdruskat/swh-save-action@8c762a62f97631c8093e6a50e7f8ffe0d231478d
  uses: sdruskat/swh-save-action@v1.0.1
          
